### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by agn-7**
- **Dockerize**
 - Update Django version
 - Update README
 - update gitignore

### CODE REVIEW

**Comment by mingchen** [comment]
Thanks for contribution.

Just one comment: Can you keep `db.sqlite3`? so when deploy to heroku there is no need to run any migration.

**Comment by agn-7** [comment]
@mingchen Thanks for your response.
Yes, I'll do that.

**Comment by agn-7** [comment]
@mingchen Hi
I reverted `sqlite` .gitignore according to your comment.

**Comment by mingchen** [comment]
Thanks.

**Pull request merged**
